name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: ['main']

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ['3.4.0.0']
        ghc: ['8.10.7']

    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: flora_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Configure environment
      run: |
        echo '/usr/lib/postgresql/12/bin/' >> $GITHUB_PATH
        echo "/nix/var/nix/profiles/per-user/$USER/profile/bin" >> "$GITHUB_PATH"
        echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"
        echo '$HOME/.ghcup/bin' >> $GITHUB_PATH
        echo 'HOME/.cabal/bin' >> $GITHUB_PATH
        echo 'HOME/.local/bin' >> $GITHUB_PATH
        echo 'NIX_PATH="nixpkgs=channel:nixos-unstable"' >> "$GITHUB_ENV"

    - name: Install Nix
      run: |
        ./.github/workflows/install-nix.sh

    - name: Configure
      run: |
        cabal configure --enable-tests --test-show-details=direct

    - name: Freeze
      run: |
        nix-shell --run 'cabal freeze'

    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Running hlint
      run: nix-shell --run './.github/workflows/hlint-runner.sh'

    - name: Running stylish-haskell
      run: nix-shell --run './.github/workflows/stylish-haskell-runner.sh'

    - name: Build
      run: |
        nix-shell --run 'make build'

    - name: Test
      run: |
        nix-shell --run 'make test'
      env:
        FLORA_DB_URI: postgres://postgres:postgres@localhost/flora_test
